# Generated by Django 5.2.13 on 2026-04-08 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mochila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Mochila', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MochilaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.item')),
                ('mochila', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mochila')),
            ],
        ),
        migrations.AddField(
            model_name='mochila',
            name='itens',
            field=models.ManyToManyField(related_name='mochilas', through='core.MochilaItem', to='core.item'),
        ),
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_saida', models.DateTimeField(auto_now_add=True)),
                ('data_retorno', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('andamento', 'Em andamento'), ('finalizada', 'Finalizada')], default='andamento', max_length=20)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.loja')),
                ('mochila', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mochila')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('status_saida', models.CharField(choices=[('pendente', 'Pendente'), ('ok', 'OK'), ('faltando', 'Faltando')], default='pendente', max_length=20)),
                ('status_retorno', models.CharField(blank=True, choices=[('pendente', 'Pendente'), ('ok', 'OK'), ('faltando', 'Faltando')], max_length=20, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.item')),
                ('viagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='core.viagem')),
            ],
        ),
    ]
