# Generated by Django 6.0.4 on 2026-04-14 14:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Loja',
                'verbose_name_plural': 'Lojas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Mochila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(default='Mochila', max_length=100)),
            ],
            options={
                'verbose_name': 'Mochila',
                'verbose_name_plural': 'Mochilas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MochilaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.item')),
                ('mochila', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mochila')),
            ],
            options={
                'unique_together': {('mochila', 'item')},
            },
        ),
        migrations.AddField(
            model_name='mochila',
            name='itens',
            field=models.ManyToManyField(related_name='mochilas', through='core.MochilaItem', to='core.item'),
        ),
        migrations.CreateModel(
            name='PasswordPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('must_change_password', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='password_policy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Política de Senha',
                'verbose_name_plural': 'Políticas de Senha',
            },
        ),
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_saida', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_retorno', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('andamento', 'Em andamento'), ('finalizada', 'Finalizada')], default='andamento', max_length=20)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.loja')),
                ('mochila', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.mochila')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Viagem',
                'verbose_name_plural': 'Viagens',
                'ordering': ['-data_saida'],
                'permissions': [('supervisor_access', 'Acesso de Supervisor (pode editar)'), ('admin_access', 'Acesso de Administrador (acesso total)'), ('finalizar_viagem', 'Pode finalizar viagens')],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('saida_ok', models.BooleanField(default=True)),
                ('retorno_ok', models.BooleanField(default=False)),
                ('observacao_retorno', models.CharField(blank=True, max_length=255)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.item')),
                ('viagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='core.viagem')),
            ],
            options={
                'verbose_name': 'Item do Checklist',
                'verbose_name_plural': 'Itens do Checklist',
                'unique_together': {('viagem', 'item')},
            },
        ),
    ]
