# Generated by Django 5.2.13 on 2026-04-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklistitem',
            old_name='observacao',
            new_name='observacao_retorno',
        ),
        migrations.RemoveField(
            model_name='checklistitem',
            name='status_retorno',
        ),
        migrations.RemoveField(
            model_name='checklistitem',
            name='status_saida',
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='retorno_ok',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='saida_ok',
            field=models.BooleanField(default=True),
        ),
    ]
