# Generated by Django 6.0.4 on 2026-04-24 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viagem',
            name='loja',
        ),
        migrations.CreateModel(
            name='ViagemLoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveSmallIntegerField(default=0, help_text='Ordem de visita da loja na viagem')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viagem_lojas', to='core.loja')),
                ('viagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viagem_lojas', to='core.viagem')),
            ],
            options={
                'verbose_name': 'Loja da Viagem',
                'verbose_name_plural': 'Lojas da Viagem',
                'ordering': ['ordem', 'id'],
                'unique_together': {('viagem', 'loja')},
            },
        ),
        migrations.AddField(
            model_name='viagem',
            name='lojas',
            field=models.ManyToManyField(related_name='viagens', through='core.ViagemLoja', to='core.loja'),
        ),
    ]
