# Generated by Django 5.2.13 on 2026-04-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_observacao_checklistitem_observacao_retorno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitem',
            name='observacao_retorno',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='retorno_ok',
            field=models.BooleanField(default=False),
        ),
    ]
