# Generated by Django 6.0.4 on 2026-04-13 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklistitem',
            options={'verbose_name': 'Item do Checklist', 'verbose_name_plural': 'Itens do Checklist'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['nome'], 'verbose_name': 'Item', 'verbose_name_plural': 'Itens'},
        ),
        migrations.AlterModelOptions(
            name='loja',
            options={'ordering': ['nome'], 'verbose_name': 'Loja', 'verbose_name_plural': 'Lojas'},
        ),
        migrations.AlterModelOptions(
            name='mochila',
            options={'ordering': ['nome'], 'verbose_name': 'Mochila', 'verbose_name_plural': 'Mochilas'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Perfil de Usuário', 'verbose_name_plural': 'Perfis de Usuários'},
        ),
        migrations.AlterModelOptions(
            name='viagem',
            options={'ordering': ['-data_saida'], 'verbose_name': 'Viagem', 'verbose_name_plural': 'Viagens'},
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='loja',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='loja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.loja'),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='mochila',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.mochila'),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
