# Generated by Django 6.0.4 on 2026-04-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_viagem_custom_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
