# Generated by Django 6.0.4 on 2026-04-13 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_item_ativo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
